model: pchk
Graph_PATH: 'mergedG_btw+clos+deg+pgr+spl.pkl'
GraphAtt_PATH: 
Feature_PATH: 
SAVEPATH: 
ENV_PATH: 
SEED: 42

# ====================
# Data Settings
# ====================
label_col: None

# Features in Table || If you don't want to use features, set it to None
node_col_name: node_id
table_features:
  - mutability
  - uniprot_id # object -> Encode
  - mut+res-bin # categorical -> Encode
  # Location
  - BHAR880101
  - CHOP780201
  - GRAR740102
  - GRAR740103
  - JANJ780101
  - KLEP840101
  - KYTJ820101
  - rel_sasa
  - depth
  - hse_up
  - hse_down
  # -> Include Null Value: fillna Applied
  - total_mutations_count
  - unique_patients_count
  - unique_mutation_types_count
  - DAYM780301_avg       # score=10^(DAYM780301_avg/10)
  - HENS920102_avg       # score=2^(HENS920102_avg/3)
  - avg_am_pathogenicity  # AlphaMissense Pathogenicity
  # - wild_type_residue # obj --> residueType
  - ptms_mapped # only have 4022 values
  # - ap_evidence_level # Too small
  # - ap_type # Too small
  # Secondary Structure
  - ss_helix
  - ss_sheet
  - ss_loop
  # - dssp_ss_bridge # Too small
  - dssp_accessibility
  - dssp_TCO
  - dssp_kappa
  - dssp_alpha
  - dssp_phi
  - dssp_psi
  - dssp_sec_struct # 8 Classes (incl NaN)
  - dssp_helix_3_10 # 4 Classes (incl NaN)
  - dssp_helix_alpha # 4 Classes (incl NaN)
  - dssp_helix_pi # 4 Classes (incl NaN)
  - dssp_helix_pp # 3 Classes (incl NaN)
  - dssp_bend # 1 Classes (incl NaN)
  - dssp_chirality # 2 Classes (incl NaN)
  - dssp_sheet # 222 Classes (incl NaN)
  - dssp_strand # 831 Classes (incl NaN)
  - dssp_ladder_1 # 614 Classes (incl NaN)
  - dssp_ladder_2 # 570 Classes (incl NaN)

bin_size: 42
uniprot_size: 800

# Features in nx.Graph as node attributes
graph_features:
  - degree
  - betweenness
  - pagerank
  - closeness_centrality
  - shortest_path_length

# Noe Attribute Normalization
node_att_norm_method: minmax # minmax or zscore
node_att_norm_target: ['degree', 'betweenness', 'closeness_centrality', 'pagerank']

# Edge Setting
use_edge_weight: False

# Train Test Split [Train, Validation, Test] (sum=1)
ratio_of_data: [0.70, 0.10, 0.20]
 
# Connected Component Setting
max_cc_size: 500000000
min_cc_size: 4

# ====================
# Data Augmentation
# ====================
use_aug: True
add_const_to_node: False
split_to_subgraphs: 
  - mut_anchored
aug_subgraph_steps: 3