model: DGI
Graph_PATH: 
GraphAtt_PATH: 
Feature_PATH: 
SAVEPATH: 
ENV_PATH: '../envs/DRC/bin/activate'
SEED: 42

# ====================
# Data Settings
# ====================

label_col: None

# Features in Table || If you don't want to use features, set it to None
node_col_name: node_id
dict_for_uniprot_to_index: 'config/uniprot-id_to_index.json'
table_features:
  - mutability
  - total_mutations_count
  - uniprot_id
  - mut+res-bin # bin=42

bin_size: 42

# Features in nx.Graph as node attributes
graph_features:
  - degree
  - shortest_path_length
  - betweenness
# - closeness

# Edge Setting
use_edge_weight: False

# Train Test Split [Train, Validation, Test] (sum=1)
ratio_of_data: [0.75, 0.15, 0.10]

# Connected Component Setting
max_cc_size: 1000
min_cc_size: 3

# ====================
# Data Augmentation
# ====================
add_const_to_node: True
split_to_subgraphs: 
  - mut_anchored