model: DGI
Graph_PATH: 
GraphAtt_PATH: 
Feature_PATH: 
SAVEPATH: 
ENV_PATH: '../envs/DRC/bin/activate'
SEED: 42

# ====================
# Data Settings
# ====================

label_col: None

# Features in Table || If you don't want to use features, set it to None
node_col_name: node_id
dict_for_uniprot_to_index: 'config/uniprot-id_to_index.json'
table_features:
  - mutability
  - uniprot_id
  - mut+res-bin
  # Location
  - BHAR880101
  - CHOP780201
  - GRAR740102
  - GRAR740103
  - JANJ780101
  - KLEP840101
  - KYTJ820101
  # Mutation -> Include Null Value --> fillna Applied
  - total_mutations_count
  - DAYM780301_avg #  DAYM780301 score=10^(DAYM780301_avg/10)
  - HENS920102_avg  # HENS920102_score=2^(HENS920102_avg/3)
  - unique_patients_count
  - unique_mutation_types_count
  # AM --> To be Updated

bin_size: 42

# Features in nx.Graph as node attributes
graph_features:
  - degree
  - shortest_path_length
  - betweenness
# - closeness

# Edge Setting
use_edge_weight: False

# Train Test Split [Train, Validation, Test] (sum=1)
ratio_of_data: [0.70, 0.15, 0.15]
 
# Connected Component Setting
max_cc_size: 50000
min_cc_size: 4

# ====================
# Data Augmentation
# ====================
add_const_to_node: True
split_to_subgraphs: 
  - mut_anchored
aug_subgraph_steps: 3